#db:
#  image: postgres
web:
  build: .
  command: python ./src/manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  environment:
    - VIRTUAL_HOST=onepi.cf,www.onepi.cf,picaday.gq,www.picaday.gq
#  links:
#    - db